# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-06 14:36:51
"""
import arcpy
from sys import argv

def DEV(Input_Raster, Neighborhood="Circle 3 MAP", Output_raster):  # DEV

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")


    # Process: Focal Statistics - Mean (Focal Statistics) (sa)
    Local_Mean = ""
    Focal_Statistics_Mean = Local_Mean
    Local_Mean = arcpy.sa.FocalStatistics(in_raster=Input_Raster, neighborhood=Neighborhood, statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
    Local_Mean.save(Focal_Statistics_Mean)


    # Process: Minus (Minus) (3d)
    Difference_from_mean = ""
    arcpy.ddd.Minus(in_raster_or_constant1=Input_Raster, in_raster_or_constant2=Local_Mean, out_raster=Difference_from_mean)
    Difference_from_mean = arcpy.Raster(Difference_from_mean)

    # Process: Focal Statistics (Focal Statistics) (sa)
    Standard_deviation = ""
    Focal_Statistics = Standard_deviation
    Standard_deviation = arcpy.sa.FocalStatistics(in_raster=Input_Raster, neighborhood=Neighborhood, statistics_type="STD", ignore_nodata="DATA", percentile_value=90)
    Standard_deviation.save(Focal_Statistics)


    # Process: Divide (Divide) (3d)
    arcpy.ddd.Divide(in_raster_or_constant1=Difference_from_mean, in_raster_or_constant2=Standard_deviation, out_raster=Output_raster)
    Output_raster = arcpy.Raster(Output_raster)

    # Process: Copy Raster (Copy Raster) (management)
    Output_Raster_Dataset = ""
    arcpy.management.CopyRaster(in_raster=Output_raster, out_rasterdataset=Output_Raster_Dataset, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\vcm\Documents\ArcGIS\Projects\HELM\HELM.gdb", workspace=r"C:\Users\vcm\Documents\ArcGIS\Projects\HELM\HELM.gdb"):
        DEV(*argv[1:])
