# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-05-27 10:38:32
"""
import arcpy
from sys import argv

def TPI(Neighborhood="Rectangle 3 3 CELL", Statistics_type="MEAN", Input_Raster):  # TPI

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")


    # Process: Focal Statistics (Focal Statistics) (sa)
    Local_Mean = ""
    Focal_Statistics = Local_Mean
    Local_Mean = arcpy.sa.FocalStatistics(in_raster=Input_Raster, neighborhood=Neighborhood, statistics_type=Statistics_type, ignore_nodata="DATA", percentile_value=90)
    Local_Mean.save(Focal_Statistics)


    # Process: Minus (Minus) (3d)
    Output_raster = "C:\\Users\\vcm\\Documents\\ArcGIS\\Projects\\HELM\\HELM.gdb\\tpi"
    arcpy.ddd.Minus(in_raster_or_constant1=Input_Raster, in_raster_or_constant2=Local_Mean, out_raster=Output_raster)
    Output_raster = arcpy.Raster(Output_raster)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\vcm\Documents\ArcGIS\Projects\HELM\HELM.gdb", workspace=r"C:\Users\vcm\Documents\ArcGIS\Projects\HELM\HELM.gdb"):
        TPI(*argv[1:])
